export const ARI_NASHI = ['なし', 'あり']
export const STATUS_CODE = {
  200: {
    message: 'success'
  },
  400: {
    message: 'リクエストにエラーがあります',
    type: 'warning'
  },
  401: {
    message: '認証に失敗しました',
    type: 'warning'
  },
  404: {
    message: '該当するリソースを見つける事ができませんでした',
    type: 'warning'
  },
  409: {
    message: '現在のリソースと競合しています',
    type: 'warning'
  },
  422: {
    message: '入力内容をもう一度確認して下さい',
    type: 'warning'
  },
  500: {
    message: '予期せぬエラーが発生しました',
    type: 'error'
  },
  503: {
    message: '現在事情によりアクセスできません',
    type: 'error'
  }
}
export const MONTH_SELECT = [
  { key: 0, value: '', label: '選択してください' },
  { key: 1, value: 1, label: '1' },
  { key: 2, value: 2, label: '2' },
  { key: 3, value: 3, label: '3' },
  { key: 4, value: 4, label: '4' },
  { key: 5, value: 5, label: '5' },
  { key: 6, value: 6, label: '6' },
  { key: 7, value: 7, label: '7' },
  { key: 8, value: 8, label: '8' },
  { key: 9, value: 9, label: '9' },
  { key: 10, value: 10, label: '10' },
  { key: 11, value: 11, label: '11' },
  { key: 12, value: 12, label: '12' }
]
export const DAY_SELECT = [
  { key: 0, value: '', label: '選択してください' },
  { key: 1, value: 1, label: '1' },
  { key: 2, value: 2, label: '2' },
  { key: 3, value: 3, label: '3' },
  { key: 4, value: 4, label: '4' },
  { key: 5, value: 5, label: '5' },
  { key: 6, value: 6, label: '6' },
  { key: 7, value: 7, label: '7' },
  { key: 8, value: 8, label: '8' },
  { key: 9, value: 9, label: '9' },
  { key: 10, value: 10, label: '10' },
  { key: 11, value: 11, label: '11' },
  { key: 12, value: 12, label: '12' },
  { key: 13, value: 13, label: '13' },
  { key: 14, value: 14, label: '14' },
  { key: 15, value: 15, label: '15' },
  { key: 16, value: 16, label: '16' },
  { key: 17, value: 17, label: '17' },
  { key: 18, value: 18, label: '18' },
  { key: 19, value: 19, label: '19' },
  { key: 20, value: 20, label: '20' },
  { key: 21, value: 21, label: '21' },
  { key: 22, value: 22, label: '22' },
  { key: 23, value: 23, label: '23' },
  { key: 24, value: 24, label: '24' },
  { key: 25, value: 25, label: '25' },
  { key: 26, value: 26, label: '26' },
  { key: 27, value: 27, label: '27' },
  { key: 28, value: 28, label: '28' },
  { key: 29, value: 29, label: '29' },
  { key: 30, value: 30, label: '30' },
  { key: 31, value: 31, label: '31' }
]
export const PREFECTURAL = [
  '不明',
  '北海道',
  '青森県',
  '岩手県',
  '宮城県',
  '秋田県',
  '山形県',
  '福島県',
  '茨城県',
  '栃木県',
  '群馬県',
  '埼玉県',
  '千葉県',
  '東京都',
  '神奈川県',
  '新潟県',
  '富山県',
  '石川県',
  '福井県',
  '山梨県',
  '長野県',
  '岐阜県',
  '静岡県',
  '愛知県',
  '三重県',
  '滋賀県',
  '京都府',
  '大阪府',
  '兵庫県',
  '奈良県',
  '和歌山県',
  '鳥取県',
  '島根県',
  '岡山県',
  '広島県',
  '山口県',
  '徳島県',
  '香川県',
  '愛媛県',
  '高知県',
  '福岡県',
  '佐賀県',
  '長崎県',
  '熊本県',
  '大分県',
  '宮崎県',
  '鹿児島県',
  '沖縄県',
  'その他'
]
export const PREFECTURAL_SELECT = [
  { key: 0, value: '', label: '選択してください' },
  { key: 1, value: 0, label: '不明' },
  { key: 2, value: 1, label: '北海道' },
  { key: 3, value: 2, label: '青森県' },
  { key: 4, value: 3, label: '岩手県' },
  { key: 5, value: 4, label: '宮城県' },
  { key: 6, value: 5, label: '秋田県' },
  { key: 7, value: 6, label: '山形県' },
  { key: 8, value: 7, label: '福島県' },
  { key: 9, value: 8, label: '茨城県' },
  { key: 10, value: 9, label: '栃木県' },
  { key: 11, value: 10, label: '群馬県' },
  { key: 12, value: 11, label: '埼玉県' },
  { key: 13, value: 12, label: '千葉県' },
  { key: 14, value: 13, label: '東京都' },
  { key: 15, value: 14, label: '神奈川県' },
  { key: 16, value: 15, label: '新潟県' },
  { key: 17, value: 16, label: '富山県' },
  { key: 18, value: 17, label: '石川県' },
  { key: 19, value: 18, label: '福井県' },
  { key: 20, value: 19, label: '山梨県' },
  { key: 21, value: 20, label: '長野県' },
  { key: 22, value: 21, label: '岐阜県' },
  { key: 23, value: 22, label: '静岡県' },
  { key: 24, value: 23, label: '愛知県' },
  { key: 25, value: 24, label: '三重県' },
  { key: 26, value: 25, label: '滋賀県' },
  { key: 27, value: 26, label: '京都府' },
  { key: 28, value: 27, label: '大阪府' },
  { key: 29, value: 28, label: '兵庫県' },
  { key: 30, value: 29, label: '奈良県' },
  { key: 31, value: 30, label: '和歌山県' },
  { key: 32, value: 31, label: '鳥取県' },
  { key: 33, value: 32, label: '島根県' },
  { key: 34, value: 33, label: '岡山県' },
  { key: 35, value: 34, label: '広島県' },
  { key: 36, value: 35, label: '山口県' },
  { key: 37, value: 36, label: '徳島県' },
  { key: 38, value: 37, label: '香川県' },
  { key: 39, value: 38, label: '愛媛県' },
  { key: 40, value: 39, label: '高知県' },
  { key: 41, value: 40, label: '福岡県' },
  { key: 42, value: 41, label: '佐賀県' },
  { key: 43, value: 42, label: '長崎県' },
  { key: 44, value: 43, label: '熊本県' },
  { key: 45, value: 44, label: '大分県' },
  { key: 46, value: 45, label: '宮崎県' },
  { key: 47, value: 46, label: '鹿児島県' },
  { key: 48, value: 47, label: '沖縄県' },
  { key: 49, value: 99, label: 'その他' }
]
